{% set version="3.2.1" %}

package:
  name: glfw3
  version: {{ version }}

source:
  fn: glfw-{{ version }}.tar.gz
  url: https://github.com/glfw/glfw/archive/{{ version }}.tar.gz
  sha256: e10f0de1384d75e6fc210c53e91843f6110d6c4f3afbfb588130713c2f9d8fe8

build:
  number: 0
  features:
    - vc9     # [win and py27]
    - vc10    # [win and py34]
    - vc14    # [win and py35]

requirements:
  build:
    - cmake
    - python      # [win]
    - msinttypes  # [win and not py35]

test:
  requires:
    - python                             # [win]

  commands:
    - test -f $PREFIX/lib/libglfw.dylib                      # [osx]
    - test -f $PREFIX/lib/libglfw.so                         # [linux]
    - if not exist %PREFIX%\\Library\\lib\\glfw3.dll exit 1  # [win]

about:
  home: http://www.glfw.org/
  license: zlib/libpng
